name: brew doctor
on:
  pull_request:
    paths:
      - .github/workflows/doctor.yml
      - Library/Homebrew/cmd/doctor.rb
      - Library/Homebrew/diagnostic.rb
      - Library/Homebrew/extend/os/diagnostic.rb
      - Library/Homebrew/extend/os/mac/diagnostic.rb
      - Library/Homebrew/os/mac/xcode.rb
permissions:
  contents: read
env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
jobs:
  tests:
    strategy:
      matrix:
        include:
          - runner: "13-arm64-${{ github.run_id }}"
          - runner: "13-${{ github.run_id }}"
          - runner: "12-arm64-${{ github.run_id }}"
          - runner: "12-${{ github.run_id }}"
          - runner: "11-arm64"
            cleanup: true
          - runner: "11-${{ github.run_id }}"
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    env:
      PATH: "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    defaults:
      run:
        working-directory: /tmp
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: false
          test-bot: true

      - run: brew test-bot --only-cleanup-before
        if: matrix.cleanup

      - run: brew doctor

      - run: brew test-bot --only-cleanup-after
        if: always() && matrix.cleanup
